# Generated by Django 4.0.4 on 2022-04-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='질문')),
                ('ques_category', models.IntegerField(choices=[(1, '일반'), (2, '계정'), (3, '기타')])),
                ('answer', models.TextField(verbose_name='답변')),
                ('writer', models.CharField(max_length=7, verbose_name='작성자')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('last_updater', models.CharField(max_length=7, verbose_name='최종 수정자')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='최종 수정일')),
            ],
        ),
    ]
