# Generated by Django 4.0.4 on 2022-04-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='last_updater',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='최종 수정자'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='writer',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='작성자'),
        ),
    ]
